# Simple workflow for deploying static content to GitHub Pages
name: Deploy documentation to Github Pages

on:
  push:
    branches: ["devel"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
     
     - name: Checkout repo (with tags)
       with:
         fetch-depth: 0

     - name: Set up Python
       run: |
          pip install sphinx==5.3.0 sphinx_rtd_theme setuptools docutils==0.17.1 sphinxcontrib.bibtex

     #- name: Install APT dependencies (doxygen, graphviz, TeX)
     #  run: |
     #    sudo apt-get update
     #    sudo apt-get install -y \
     #      doxygen doxygen-doc doxygen-latex \
     #      graphviz \
     #      texlive texlive-latex-extra latexmk

     - name: Install Python dependencies (Sphinx toolchain)
       run: |
         python -m pip install --upgrade pip
         pip install sphinx sphinx_rtd_theme sphinx-numfig sphinxcontrib-bibtex

     - name: Sphinx build
       run: |
          cd docs/sphinx_doc && make html

     #- name: Doxygen build
     #  run: |
     #     cd docs/doxygen && doxygen doxygen.conf

     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
       with:
         publish_branch: gh-pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: docs/sphinx_doc/build/html
         force_orphan: true


